#!/usr/bin/env python3
"""Generate or verify the physical banks and self-contained H64 ROM RTL."""

from __future__ import annotations

import argparse
from pathlib import Path


ROWS = 256
BANKS = 8
# Split each 264-bit logical model bank into two 132-bit physical ROMs. The
# packed row order is unchanged: bank 2*n holds weights 0..32 for logical
# model bank n and bank 2*n+1 holds weights 33..65.
BANK_HEX_DIGITS = 132 // 4
DEFAULT_ROM = Path("src/main/resources/h64-residual-weights-int4.hex")
DEFAULT_OUTPUT_DIR = Path("src/main/resources")
ROM_RTL_NAME = "H64WeightRom.sv"


def bank_path(output_dir: Path, bank: int) -> Path:
    return output_dir / f"h64-residual-weights-int4-bank{bank}.hex"


def read_rows(path: Path, expected_width: int) -> list[str]:
    rows = [line.strip().lower() for line in path.read_text(encoding="ascii").splitlines()]
    if len(rows) != ROWS:
        raise ValueError(f"{path}: expected {ROWS} rows, found {len(rows)}")
    for row_index, row in enumerate(rows):
        if len(row) != expected_width:
            raise ValueError(
                f"{path}:{row_index + 1}: expected {expected_width} hex digits, "
                f"found {len(row)}"
            )
        try:
            int(row, 16)
        except ValueError as error:
            raise ValueError(f"{path}:{row_index + 1}: invalid hexadecimal row") from error
    return rows


def split_rows(rows: list[str]) -> list[list[str]]:
    split = [[] for _ in range(BANKS)]
    for row in rows:
        # Packed Verilog rows are printed MSB first, while Scala modelRows(0)
        # consumes the least-significant 264 bits.
        for bank in range(BANKS):
            right = len(row) - bank * BANK_HEX_DIGITS
            left = right - BANK_HEX_DIGITS
            split[bank].append(row[left:right])
    return split


def render_rom_rtl(banks: list[list[str]], source_name: str) -> str:
    lines = [
        "// Generated by scripts/split-h64-rom-banks.py from " + source_name + ".",
        "// Do not edit this file directly; regenerate it from the canonical ROM image.",
        "// Literal initialization keeps FPGA synthesis independent of external MIF paths.",
        "",
    ]

    for bank, rows in enumerate(banks):
        lines.extend(
            [
                f"module H64WeightRomBank{bank} (",
                "  input  wire         clock,",
                "  input  wire         enable,",
                "  input  wire [7:0]   address,",
                "  output reg  [131:0] data",
                ");",
                "  (* rom_style = \"block\" *) reg [131:0] memory [0:255];",
                "",
                "  initial begin",
            ]
        )
        lines.extend(
            f"    memory[8'h{address:02x}] = 132'h{row};"
            for address, row in enumerate(rows)
        )
        lines.extend(
            [
                "  end",
                "",
                "  always @(posedge clock) begin",
                "    if (enable)",
                "      data <= memory[address];",
                "  end",
                "endmodule",
                "",
            ]
        )

    lines.extend(
        [
            "module H64WeightRom (",
            "  input  wire          clock,",
            "  input  wire          enable,",
            "  input  wire [7:0]    address,",
            "  output wire [1055:0] data",
            ");",
        ]
    )
    lines.extend(f"  wire [131:0] bank{bank}_data;" for bank in range(BANKS))
    lines.append("")
    for bank in range(BANKS):
        lines.extend(
            [
                f"  H64WeightRomBank{bank} bank{bank} (",
                "    .clock(clock), .enable(enable), .address(address), "
                f".data(bank{bank}_data)",
                "  );",
            ]
        )
    lines.extend(
        [
            "",
            "  assign data = {",
            "    bank7_data, bank6_data, bank5_data, bank4_data,",
            "    bank3_data, bank2_data, bank1_data, bank0_data",
            "  };",
            "endmodule",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rom", type=Path, default=DEFAULT_ROM)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify checked-in bank files without modifying them",
    )
    args = parser.parse_args()

    source_rows = read_rows(args.rom, BANKS * BANK_HEX_DIGITS)
    expected_banks = split_rows(source_rows)
    reconstructed = [
        "".join(expected_banks[bank][row] for bank in reversed(range(BANKS)))
        for row in range(ROWS)
    ]
    if reconstructed != source_rows:
        raise AssertionError("internal bank reconstruction changed the packed ROM")

    expected_rtl = render_rom_rtl(expected_banks, args.rom.name)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    for bank, expected_rows in enumerate(expected_banks):
        path = bank_path(args.output_dir, bank)
        if args.check:
            actual_rows = read_rows(path, BANK_HEX_DIGITS)
            if actual_rows != expected_rows:
                raise ValueError(f"{path}: bank contents do not match {args.rom}")
        else:
            path.write_text("\n".join(expected_rows) + "\n", encoding="ascii")

    rtl_path = args.output_dir / ROM_RTL_NAME
    if args.check:
        actual_rtl = rtl_path.read_text(encoding="ascii")
        if actual_rtl != expected_rtl:
            raise ValueError(f"{rtl_path}: generated RTL does not match {args.rom}")
    else:
        rtl_path.write_text(expected_rtl, encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
