package gemmont.debug

import chisel3._
import chisel3.util.HasBlackBoxResource

class PerformanceCounterSink extends BlackBox with HasBlackBoxResource {
  override def desiredName: String = "PerformanceCounterSink"

  val io = IO(new Bundle {
    val clock = Input(Clock())
    val reset = Input(Bool())

    val cycle = Input(UInt(64.W))
    val fetchPc = Input(UInt(32.W))
    val retirePc = Input(UInt(96.W))
    val retireCounterValue = Input(UInt(96.W))
    val retireValid = Input(UInt(3.W))
    val retireCounter = Input(UInt(3.W))
    val branchRetired = Input(Bool())
    val mispredictRetired = Input(Bool())
    val branchMispredictRetired = Input(Bool())
    val otherRecovery = Input(Bool())
    val h64LateCorrection = Input(Bool())
    val h64RenameFire = Input(UInt(3.W))
    val h64RenameEvaluated = Input(UInt(3.W))
    val h64RenameRobIndex = Input(UInt(15.W))
    val h64RenameFastTaken = Input(UInt(3.W))
    val h64RenameNeuralTaken = Input(UInt(3.W))
    val h64RenameReliable = Input(UInt(3.W))
    val h64RenameOverride = Input(UInt(3.W))
    val h64DecodeFire = Input(UInt(3.W))
    val h64DecodeRobIndex = Input(UInt(15.W))
    val h64DecodePc = Input(UInt(96.W))
    val h64DecodeToken = Input(UInt(12.W))
    val h64DecodeEpoch = Input(UInt(9.W))
    val h64DecodeWay = Input(UInt(6.W))
    val h64DecodeHistory = Input(UInt(192.W))
    val h64DecodePath = Input(UInt(96.W))
    val h64DecodeScore = Input(UInt(33.W))
    val h64DecodePhtCounter = Input(UInt(6.W))
    val h64DecodeFastTaken = Input(UInt(3.W))
    val h64DecodeNeuralTaken = Input(UInt(3.W))
    val h64DecodeReliable = Input(UInt(3.W))
    val h64DecodeOverride = Input(UInt(3.W))
    val h64DecodeDirectionBias = Input(UInt(3.W))
    val h64RetireActualTaken = Input(UInt(3.W))
    val retireRobIndex = Input(UInt(5.W))
    val mispredictResolved = Input(UInt(3.W))
    val mispredictResolvedRob = Input(UInt(15.W))

    val frontendValid = Input(UInt(3.W))
    val dispatchBlocked = Input(Bool())
    val robOccupancy = Input(UInt(6.W))
    val integerIssueOccupancy = Input(UInt(3.W))
    val mulDivIssueOccupancy = Input(UInt(2.W))
    val memoryIssueOccupancy = Input(UInt(3.W))
    val storeBufferOccupancy = Input(UInt(4.W))
    val integerIssue = Input(UInt(3.W))
    val mulDivIssue = Input(Bool())
    val memoryIssue = Input(Bool())
    val memoryIssueOperandsReady = Input(Bool())
    val memoryIssueAddressReady = Input(Bool())
    val memoryIssueDataReady = Input(Bool())
    val memoryIssueLsuReady = Input(Bool())
    val memoryIssueHeadPc = Input(UInt(32.W))

    val speculativeWakeupFailed = Input(Bool())
    val mem2Valid = Input(Bool())
    val mem2Pc = Input(UInt(32.W))
    val mem2CacheWait = Input(Bool())
    val mem2StoreBufferWait = Input(Bool())
    val mem2AuxWait = Input(Bool())

    val instructionCacheRequest = Input(Bool())
    val instructionCacheHit = Input(Bool())
    val instructionCacheMiss = Input(Bool())
    val instructionCacheMissBusy = Input(Bool())
    val dataCacheRequest = Input(Bool())
    val dataCacheHit = Input(Bool())
    val dataCacheMiss = Input(Bool())
    val dataCacheMissBusy = Input(Bool())
    val dataCacheRefillBusy = Input(Bool())
    val dataCachePostResponseRefillBusy = Input(Bool())
    val dataCacheDirectRefill = Input(Bool())
    val dataCacheEarlyResponse = Input(Bool())
    val dataCacheDirtyWriteback = Input(Bool())
    val dataCacheDirtyVictim = Input(Bool())
    val dataCacheTailBlockedWouldHit = Input(Bool())
    val dataCacheTailBlockedSameFillLine = Input(Bool())
    val dataCacheTailBlockedNewMiss = Input(Bool())
    val dataCacheTailBlockedStore = Input(Bool())
    val dataCacheDirtyVictimCaptureBusy = Input(Bool())
    val dataCacheDirtyVictimReadAddressWait = Input(Bool())
    val dataCacheDirtyVictimResponseWait = Input(Bool())
    val dataCacheLoadMiss = Input(Bool())
    val dataCacheStoreMiss = Input(Bool())
    val dataCacheLoadMissPlusOne = Input(Bool())
    val dataCacheLoadMissMinusOne = Input(Bool())
    val dataCacheLoadMissRepeat = Input(Bool())
    val dataCachePrefetchCandidate = Input(Bool())
    val dataCachePrefetchRequest = Input(Bool())
    val dataCachePrefetchL2Hit = Input(Bool())
    val dataCachePrefetchL2Miss = Input(Bool())
    val dataCachePrefetchBufferHit = Input(Bool())
    val dataCachePrefetchLate = Input(Bool())
    val dataCachePrefetchDropped = Input(Bool())
    val dataCachePrefetchDuplicate = Input(Bool())
    val dataCachePrefetchPageSuppressed = Input(Bool())
    val dataCachePrefetchCancelled = Input(Bool())
    val dataCachePrefetchUseless = Input(Bool())

    val l2InstructionRead = Input(Bool())
    val l2InstructionHit = Input(Bool())
    val l2InstructionMiss = Input(Bool())
    val l2InstructionMissBusy = Input(Bool())
    val l2DataRead = Input(Bool())
    val l2DataHit = Input(Bool())
    val l2DataDirectHit = Input(Bool())
    val l2DataMiss = Input(Bool())
    val l2DataMissBusy = Input(Bool())
    val l2DataWrite = Input(Bool())
    val l2DirtyWriteback = Input(Bool())
    val l2ReadAddress = Input(UInt(32.W))
    val l2DataWriteAddress = Input(UInt(32.W))
    val l2ReadMissBusy = Input(Bool())
    val l2WriteBusy = Input(Bool())
    val l2DataPrefetchRead = Input(Bool())
    val l2DataPrefetchHit = Input(Bool())
    val l2DataPrefetchMiss = Input(Bool())
    val l2DataPrefetchWait = Input(Bool())
    val l2InstructionReadWait = Input(Bool())
    val l2InstructionReadWaitAddress = Input(UInt(32.W))
    val l2DataReadWait = Input(Bool())
    val l2DataReadWaitAddress = Input(UInt(32.W))
  })

  addResource("/PerformanceCounterSink.sv")
}
