package gemmont.debug

import chisel3._

class FrontendProfileObservation extends Bundle {
  val h64Valid = UInt(3.W)
  val h64Pc = UInt(96.W)
  val h64Token = UInt(12.W)
  val h64Epoch = UInt(9.W)
  val h64Way = UInt(6.W)
  val h64History = UInt(192.W)
  val h64Path = UInt(96.W)
  val h64Score = UInt(33.W)
  val h64PhtCounter = UInt(6.W)
  val h64FastTaken = UInt(3.W)
  val h64NeuralTaken = UInt(3.W)
  val h64Reliable = UInt(3.W)
  val h64Override = UInt(3.W)
  val h64DirectionBias = UInt(3.W)
}

class DecodeProfileObservation extends Bundle {
  val idFire = UInt(3.W)
  val renameFire = Bool()
  val renameRobIndex = UInt(15.W)
}

class ExecutionProfileObservation extends Bundle {
  val integerIssue = UInt(3.W)
  val integerExeRob = UInt(15.W)
  val integerMispredict = UInt(3.W)
  val mduIssue = Bool()
}

class LsuProfileObservation extends Bundle {
  val issue = Bool()
  val mem2Valid = Bool()
  val mem2Pc = UInt(32.W)
  val mem2CacheWait = Bool()
  val mem2StoreBufferWait = Bool()
  val mem2AuxWait = Bool()
}

class CacheProfileObservation extends Bundle {
  val request = Bool()
  val hit = Bool()
  val miss = Bool()
  val missBusy = Bool()
  val refillBusy = Bool()
  val postResponseRefillBusy = Bool()
  val directRefill = Bool()
  val earlyResponse = Bool()
  val dirtyWriteback = Bool()
  val dirtyVictim = Bool()
  val tailBlockedWouldHit = Bool()
  val tailBlockedSameFillLine = Bool()
  val tailBlockedNewMiss = Bool()
  val tailBlockedStore = Bool()
  val dirtyVictimCaptureBusy = Bool()
  val dirtyVictimReadAddressWait = Bool()
  val dirtyVictimResponseWait = Bool()
  val loadMiss = Bool()
  val storeMiss = Bool()
  val loadMissPlusOne = Bool()
  val loadMissMinusOne = Bool()
  val loadMissRepeat = Bool()
  val prefetchCandidate = Bool()
  val prefetchRequest = Bool()
  val prefetchL2Hit = Bool()
  val prefetchL2Miss = Bool()
  val prefetchBufferHit = Bool()
  val prefetchLate = Bool()
  val prefetchDropped = Bool()
  val prefetchDuplicate = Bool()
  val prefetchPageSuppressed = Bool()
  val prefetchCancelled = Bool()
  val prefetchUseless = Bool()
}

class L2ProfileObservation extends Bundle {
  val instructionRead = Bool()
  val instructionHit = Bool()
  val instructionMiss = Bool()
  val instructionMissBusy = Bool()
  val dataRead = Bool()
  val dataHit = Bool()
  val dataDirectHit = Bool()
  val dataMiss = Bool()
  val dataMissBusy = Bool()
  val dataWrite = Bool()
  val dirtyWriteback = Bool()
  val readAddress = UInt(32.W)
  val dataWriteAddress = UInt(32.W)
  val readMissBusy = Bool()
  val writeBusy = Bool()
  val dataPrefetchRead = Bool()
  val dataPrefetchHit = Bool()
  val dataPrefetchMiss = Bool()
  val dataPrefetchWait = Bool()
}

class CacheInterconnectProfileObservation extends Bundle {
  val instructionReadWait = Bool()
  val instructionReadWaitAddress = UInt(32.W)
  val dataReadWait = Bool()
  val dataReadWaitAddress = UInt(32.W)
}

class CoreProfileObservation extends Bundle {
  val cycle = UInt(64.W)
  val fetchPc = UInt(32.W)
  val retirePc = UInt(96.W)
  val retireCounterValue = UInt(96.W)
  val retireValid = UInt(3.W)
  val retireCounter = UInt(3.W)
  val branchRetired = Bool()
  val mispredictRetired = Bool()
  val branchMispredictRetired = Bool()
  val otherRecovery = Bool()
  val h64LateCorrection = Bool()
  val h64RenameFire = UInt(3.W)
  val h64RenameEvaluated = UInt(3.W)
  val h64RenameRobIndex = UInt(15.W)
  val h64RenameFastTaken = UInt(3.W)
  val h64RenameNeuralTaken = UInt(3.W)
  val h64RenameReliable = UInt(3.W)
  val h64RenameOverride = UInt(3.W)
  val h64DecodeFire = UInt(3.W)
  val h64DecodeRobIndex = UInt(15.W)
  val h64DecodePc = UInt(96.W)
  val h64DecodeToken = UInt(12.W)
  val h64DecodeEpoch = UInt(9.W)
  val h64DecodeWay = UInt(6.W)
  val h64DecodeHistory = UInt(192.W)
  val h64DecodePath = UInt(96.W)
  val h64DecodeScore = UInt(33.W)
  val h64DecodePhtCounter = UInt(6.W)
  val h64DecodeFastTaken = UInt(3.W)
  val h64DecodeNeuralTaken = UInt(3.W)
  val h64DecodeReliable = UInt(3.W)
  val h64DecodeOverride = UInt(3.W)
  val h64DecodeDirectionBias = UInt(3.W)
  val h64RetireActualTaken = UInt(3.W)
  val retireRobIndex = UInt(5.W)
  val mispredictResolved = UInt(3.W)
  val mispredictResolvedRob = UInt(15.W)

  val frontendValid = UInt(3.W)
  val dispatchBlocked = Bool()
  val robOccupancy = UInt(6.W)
  val integerIssueOccupancy = UInt(3.W)
  val mulDivIssueOccupancy = UInt(2.W)
  val memoryIssueOccupancy = UInt(3.W)
  val storeBufferOccupancy = UInt(4.W)
  val integerIssue = UInt(3.W)
  val mulDivIssue = Bool()
  val memoryIssue = Bool()
  val memoryIssueOperandsReady = Bool()
  val memoryIssueAddressReady = Bool()
  val memoryIssueDataReady = Bool()
  val memoryIssueLsuReady = Bool()
  val memoryIssueHeadPc = UInt(32.W)

  val speculativeWakeupFailed = Bool()
  val mem2Valid = Bool()
  val mem2Pc = UInt(32.W)
  val mem2CacheWait = Bool()
  val mem2StoreBufferWait = Bool()
  val mem2AuxWait = Bool()
  val instructionCache = new CacheProfileObservation
  val dataCache = new CacheProfileObservation
}
